config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'top' => 'homes#top'
  resources :books do
    member do
      get 'edit'
    end
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end

  def show
    @book = Book.find(params[:id])  
  end

  def edit
    @book = Book.find(params[:id])  
  end

  def update
    puts params[:id]
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to @book
    else
      @books = Book.all
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id]) 
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book && @book.errors.any? %>
<%= @book.errors.count %>error prohibited this book from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @book, url: book_path(@book), method: :patch do |f| %>
    <%= f.hidden_field :id %>
    <p>Title</p>
    <%= f.text_field :title %>
      
    <p>Body</p>
    <%= f.text_area :body %>

    <p>
    <%= f.submit 'Update Book' %>
    <p/>
  <% end %>

<%= link_to "Show", @book %>
❘
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h3>Books</h3>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
       <% @books.each do |book| %>
          <tr>
            <td> <%= book.title %> </td>
            <td> <%= book.body %> </td>
            <td> <%= link_to "Show", book_path(book.id) %>
                 <%= link_to "Edit", edit_book_path(book.id) %>
                 <%= link_to "Destroy",
              book_path(book.id), 
              method: :delete, 
              "data-confirm" => "Are you sure?" %>
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>

<h4>New Book</h4>
<% if @book && @book.errors.any? %>
<%= @book.errors.count %>error prohibited this book from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>


<%= form_with model: @book, url: books_path do |f| %>
  <p>Title</p>
  <%= f.text_field 'book[title]' %>
	
  <p>Body</p>
  <%= f.text_area 'book[body]' %>
	
  <p>
  <%= f.submit 'Create Book' %>
  <p/>
<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book) %>
❘
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ
  Bookersへ！
</h1>

 <p>
   <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や
 <p>

 <p>印象を共有し交換することができます<p/>

 <p>
   <%= link_to "start", books_path %>
 <p/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>